#! ruby
require 'test/unit'
require 'gtk2mp3'

class TestVersion < Test::Unit::TestCase
  def test_version
    assert_nothing_raised() do
      version = '1.4.0'
      assert_equal version, Gtk2Mp3::VERSION
      assert_equal version, File.read('./data/VERSION').strip
    end
  end
end
