#! ruby
require 'test/unit'
require 'gtk2mp3'

class TestVersion < Test::Unit::TestCase
  def test_version
    version = '1.5.0'
    assert_equal version, Gtk2Mp3::VERSION
    assert_equal version, File.read('./data/VERSION').strip
    assert_equal version, `gtk2mp3 --version`.strip
  end
end
